FROM quay.io/toolbx-images/alpine-toolbox:edge

RUN apk add jq curl curlie wget cosign github-cli caddy git openssh
RUN apk add nodejs go nim rustup python3
RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -